PRIMARY_BLUE = "#008000"
ACCENT_GREEN = "#38A169"
BG_LIGHT = "#F5F6FA"
TEXT_DARK = "#2D3748"
CARD_BG = "#FFFFFF"

REQUIRED_MAX_DEFAULTS: dict[str, float] = {}
REQUIRED_MIN_DEFAULTS: dict[str, float] = {}
INTRANSIT_DEFAULTS: dict[str, float] = {}

GLOBAL_REQUIRED_MAX_FALLBACK = 10000
GLOBAL_REQUIRED_MIN_FALLBACK = 0
GLOBAL_INTRANSIT_FALLBACK = 0

RAW_INVENTORY_TABLE = "CONSUMPTION.HFS_COMMERCIAL_INVENTORY.APP_INVENTORY"
SNOWFLAKE_ADMIN_CONFIG_TABLE = "CONSUMPTION.HFS_COMMERCIAL_INVENTORY.APP_SUPERADMIN_CONFIG"
SQLITE_ADMIN_CONFIG_TABLE = "APP_SUPERADMIN_CONFIG"
